---
- name: Install Node Exporter and update Prometheus configuration
  hosts: all
  become: yes
  tasks:
    - name: Include Node Exporter role
      include_role:
        name: node_exporter
      when: "'prometheus_nodes' in group_names"

    - name: Include Update Prometheus role
      include_role:
        name: update_prometheus
      when: "'prometheus_server' in group_names"